
[Rewards]

	#Set to false to disable a specific reward
	[Rewards."General Settings"]
		#Don't touch! Well I mean you can touch it, if you want. I can't stop you. I'm only text.
		HolidayRewardTriggered = false
		#Set to false if you wish to disable the super special holiday rewards. Why would you want to do that?
		HolidayRewards = true
		#Set to true if the D20's should have any chance value from -100 to 100. Set to false to have the D20's only have a chance value of either -100 or 100
		D20UseNormalChanceValues = false
		#Number of uses for a pendant
		pendantUses = 32
		#True if Chance Cubes should load in user specific rewards (for a select few only)
		UserSpecificRewards = true
		#True if Chance Cubes should have a crafting recipe. false if they should not
		CraftingRecipe = true
		#The minimum chance range value. Changes the range of chance that the chance block can pick from. i.e. If you have your rangemin set to 10 and range max set to 15. A chance cube with a chance value of 0 can get rewards of -10 to 15 in chance value.
		chanceRangeMin = 10
		#true if Chance Cubes should generate on the surface of the world. false if they should not
		GenerateOnSurface = true
		#Amount of chance cubes to try and spawn, per chunk, as an ore
		oreGenAmount = 4
		#Set to true if the default rewards should be loaded, false if they shouldn't
		EnableDefaultRewards = true
		#True if Chance Cubes should generate as chest loot in the world. false if they should not
		ChestLoot = true
		#Chance of a chunk to have a chance cube spawned on the surface. The math is 1/(surfaceGenerationAmount), so increase to make more rare, and decrese to make more common.
		surfaceGenerationAmount = 100
		#True if Chance Cubes should generate like ores with in the world. false if they should not
		GenerateAsOre = true
		#The maximum chance range value. Changes the range of chance that the chance block can pick from. i.e. If you have your rangemin set to 10 and range max set to 15. A chance cube with a chance value of 0 can get rewards of -10 to 15 in chance value.
		chanceRangeMax = 10
		#Worlds that Chance cubes shold not generate in
		BlockedWorlds = []
		#True if Chance Cubes should check for globally disabled rewards (Rewards that are usually bugged or not working correctly). NOTE: The mod sends your Chance Cubes mod version to the web server to check for disabled rewards for your given version and the version number is subsequently logged. Feel free to make an inquiry if you wish to know more.
		GloballyDisabledRewards = true
		#How many blocks above the Chance Cube that a block that will fall should be dropped from
		FallingBlockDropHeight = 20

