
#Client only settings, mostly things related to rendering
[client]
	#Disable culling of hidden faces next to stairs and slabs. Causes extra rendering, but may fix some resource packs that exploit this vanilla mechanic.
	disableStairSlabCulling = false
	#Allow item rendering to detect emissive quads and draw them properly. This allows glowing blocks to look the same in item form, but incurs a very slight performance hit.
	allowEmissiveItems = true
	#Toggle off to make missing model text in the gui fit inside the slot.
	zoomInMissingModelTextInGui = false
	#Enable forge to queue all chunk updates to the Chunk Update thread.
	#May increase FPS significantly, but may also cause weird rendering lag.
	#Not recommended for computers without a significant number of cores available.
	alwaysSetupTerrainOffThread = false
	#Enable the forge block rendering pipeline - fixes the lighting of custom models.
	forgeLightPipelineEnabled = true
	#When enabled, forge will show any warnings that occurred during loading
	showLoadWarnings = true
	#Enable uploading cloud geometry to the GPU for faster rendering.
	forgeCloudsEnabled = true
	#When enabled, makes specific reload tasks such as language changing quicker to run.
	selectiveResourceReloadEnabled = true

